language: python

python:
  - 3.7

script:
  - "./gradlew dist"

before_install:
  - pip install pygments

install:
  - echo sonatypeUsername=none >> gradle.properties
  - echo sonatypePassword=none >> gradle.properties

deploy:
  provider: releases
  api_key:
    secure: BkAXFJuzGZ8H9dq253uqlJ3pp8WKphOwydKlC4poSczG4ps57eZ+yxeJ/IOWbO/s789c/E8q0k8IbhIZol8pHX0C+4jPdBkmrb1k7AfhSZnViJxDzw4r1hbtlITmuCfWAAK48NW1iDE23WxS5qpO4YgMfipMlT/nEJ9te73FGThl1xxhbLwSEnccd06SBKmsoK+kNX3KKpa7fdu3gc2BZoSU3kd6CHONemQnJp0F5H7JH2DtADWDizB90AADslOmcCy+17ornsDF0akCKOCIIYpaCCAQjKSNZSlCSDTxJvS2syXUxsllDfjiqIBCL9yVF+VDyVW2wr6ap009Ag86G1YjSXqRJHuM/dclHw//tGKrWDrckNb8R1FP7cxT9WdJpCZXblhCNN5+eLz6Qc4ZkyrcBM/e9c8LsHpZ4afYp7ZCa9Ste7w5qHKRTuRJnjGCxVz8QRccjhsPJ5qCFc8wmkVwCaKo/Ip6+ISamo9L1rcYDPKu5aSBNVpLYtkbreM6FFArhXYgjGBSqhRKwCJJfIFW8c/1fP4u3gl/UyPoOuESDE5BekBiYeRZKJ8CRVjTX0gkdHxB2rDJSnMyGRVyJI7TzoYYZmBjkqOsJ79BGJZ4z/A4OxOhfz24PXXCCUE2v6PpQXiZ4BBrNPlIPptphiXuV6V7yhKqeiWbowQ/TH0=
  skip_cleanup: true
  file: build/distributions/xmlcalabash1-pygments-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true

